{"name": "test_true", "status": "failed", "statusDetails": {"message": "AssertionError: assert False == True\n  +False\n  -True", "trace": "self = <test_leap_year.TestAssert object at 0x000001C4E379F048>\n\n    @pytest.mark.run(order=1)\n    def test_true(self):\n>       assert is_leap_year(2017) == True\nE       assert False == True\nE         +False\nE         -True\n\ntest_leap_year.py:36: AssertionError"}, "start": 1588053903184, "stop": 1588053903185, "uuid": "e190dad3-afe4-433b-a1a1-d11bab4d08a0", "historyId": "9db7ba8602f272ed967dcdafbb3f3521", "testCaseId": "34603d2208cc04ae1d25f5b0c05a0fa3", "fullName": "test_leap_year.TestAssert#test_true", "labels": [{"name": "suite", "value": "test_leap_year"}, {"name": "subSuite", "value": "TestAssert"}, {"name": "host", "value": "PC-BFD8TY2"}, {"name": "thread", "value": "16124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_leap_year"}]}