{"name": "test_true", "status": "failed", "statusDetails": {"message": "AssertionError: assert False == True\n  +False\n  -True", "trace": "self = <test_leap_year.TestAssert object at 0x0000028E19A66148>\n\n    @pytest.mark.run(order=3)\n    def test_true(self):\n>       assert is_leap_year(2017) == True\nE       assert False == True\nE         +False\nE         -True\n\ntest_leap_year.py:36: AssertionError"}, "start": 1588053929005, "stop": 1588053929006, "uuid": "99c23a3f-1d01-45f4-b157-4c9a93de6a3f", "historyId": "9db7ba8602f272ed967dcdafbb3f3521", "testCaseId": "34603d2208cc04ae1d25f5b0c05a0fa3", "fullName": "test_leap_year.TestAssert#test_true", "labels": [{"name": "suite", "value": "test_leap_year"}, {"name": "subSuite", "value": "TestAssert"}, {"name": "host", "value": "PC-BFD8TY2"}, {"name": "thread", "value": "404-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_leap_year"}]}