{"name": "test_exception_match", "status": "failed", "statusDetails": {"message": "AssertionError: Pattern '公元33元年是从公元一年开始' does not match '公元元年是从公元一年开始的'", "trace": "self = <test_leap_year.TestAssert object at 0x000001BA55889688>\n\n    def test_exception_match(self):\n        with pytest.raises(ValueError, match='公元33元年是从公元一年开始') as excinfo:\n>           is_leap_year(0)\n\ntest_leap_year.py:46: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nyear = 0\n\n    def is_leap_year(year):\n        if isinstance(year, int) is not True:\n            raise TypeError(\"传入的参数不是整数\")\n        elif year == 0:\n>           raise ValueError(\"公元元年是从公元一年开始的\")\nE           ValueError: 公元元年是从公元一年开始的\n\ntest_leap_year.py:16: ValueError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_leap_year.TestAssert object at 0x000001BA55889688>\n\n    def test_exception_match(self):\n        with pytest.raises(ValueError, match='公元33元年是从公元一年开始') as excinfo:\n            is_leap_year(0)\n>           assert excinfo.type == ValueError\nE           AssertionError: Pattern '公元33元年是从公元一年开始' does not match '公元元年是从公元一年开始的'\n\ntest_leap_year.py:47: AssertionError"}, "start": 1588052568688, "stop": 1588052568688, "uuid": "9e459b1e-001c-4870-835e-a2f80f3c6d6e", "historyId": "0bc83563d379e090cbbc3dd4fb9c58b2", "testCaseId": "7ad40325dbda3229eb4244c14bc09640", "fullName": "test_leap_year.TestAssert#test_exception_match", "labels": [{"name": "suite", "value": "test_leap_year"}, {"name": "subSuite", "value": "TestAssert"}, {"name": "host", "value": "PC-BFD8TY2"}, {"name": "thread", "value": "12328-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_leap_year"}]}